In [1]:
from earlywarn.classification.early_classification._probability_treshold import ProbabilityThresholdEarlyClassifier

In [2]:
from aeon.classification.interval_based import TimeSeriesForestClassifier

In [3]:
from aeon.datasets import load_unit_test

In [4]:
X_train, y_train = load_unit_test(split="train")

In [5]:
X_test, y_test = load_unit_test(split="test")

In [6]:
X_train.shape, y_train.shape

((20, 1, 24), (20,))

In [7]:
y_train

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2',
       '2', '2', '2', '2', '2', '2', '2'], dtype='<U1')

In [8]:
clf = ProbabilityThresholdEarlyClassifier(
    classification_points=[6, 16, 24],
    estimator=TimeSeriesForestClassifier(n_estimators=5),
    )

In [9]:
clf.fit(X_train, y_train)

ProbabilityThresholdEarlyClassifier(classification_points=[6, 16, 24],
                                    estimator=TimeSeriesForestClassifier(n_estimators=5))

In [10]:
X_test.shape, y_test.shape

((22, 1, 24), (22,))

In [11]:
y_pred = clf.predict(X_test)

In [12]:
y_pred

(array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2',
        '2', '1', '2', '2', '1', '2', '2', '2', '2'], dtype='<U1'),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]))

In [13]:
X_test.shape

(22, 1, 24)

In [14]:
clf.state_info # shape (n_cases, 4) with columns: 'time_stamp_idx', 'consecutive', 'predicted_label', 'time_stamp'

array([[ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  1,  6],
       [ 0,  1,  1,  6],
       [ 2,  1,  0, 24],
       [ 0,  1,  1,  6],
       [ 0,  1,  1,  6],
       [ 0,  1,  0,  6],
       [ 0,  1,  1,  6],
       [ 0,  1,  1,  6],
       [ 0,  1,  1,  6],
       [ 0,  1,  1,  6]])

In [15]:
clf.state_info.shape

(22, 4)

In [16]:
from earlywarn.data._dataset import Dataset

In [17]:
import os
import numpy as np
os.getcwd()

'/home/joffreyma/Codes/EarlyWarn/notebooks'

In [18]:
train_data_path = "../data/nasa_cmapss/train_FD001.txt"

In [19]:
train = Dataset(train_data_path)

In [20]:
train.data

array([[ 1.00000e+00,  1.00000e+00, -7.00000e-04, ...,  1.00000e+02,
         3.90600e+01,  2.34190e+01],
       [ 1.00000e+00,  2.00000e+00,  1.90000e-03, ...,  1.00000e+02,
         3.90000e+01,  2.34236e+01],
       [ 1.00000e+00,  3.00000e+00, -4.30000e-03, ...,  1.00000e+02,
         3.89500e+01,  2.33442e+01],
       ...,
       [ 5.00000e+01,  1.96000e+02,  2.00000e-03, ...,  1.00000e+02,
         3.84500e+01,  2.30379e+01],
       [ 5.00000e+01,  1.97000e+02, -2.60000e-03, ...,  1.00000e+02,
         3.85200e+01,  2.30832e+01],
       [ 5.00000e+01,  1.98000e+02,  3.90000e-03, ...,  1.00000e+02,
         3.84300e+01,  2.31086e+01]], shape=(9909, 26))

In [21]:
X1, y1 = train[1]

In [22]:
X1.shape, y1.shape

((25, 386), (386,))

In [23]:
from earlywarn.classification.compose.prefix_ensemble import ProgressivePrefixEnsembleClassifier

In [24]:
ppeclf = ProgressivePrefixEnsembleClassifier()

In [25]:
prefix_max_length = 100

In [26]:
X_example = [X1[:, i:i+prefix_max_length] for i in range(X1.shape[1]-prefix_max_length+1)]
y_example = [y1[i] for i in range(prefix_max_length-1, X1.shape[1])]

In [27]:
X_example[-1], y_example[-1]

(array([[ 2.87000e+02,          nan,          nan, ...,          nan,
                  nan,          nan],
        [-5.00000e-04,          nan,          nan, ...,          nan,
                  nan,          nan],
        [ 6.00000e-04,          nan,          nan, ...,          nan,
                  nan,          nan],
        ...,
        [ 1.00000e+02,          nan,          nan, ...,          nan,
                  nan,          nan],
        [ 3.84300e+01,          nan,          nan, ...,          nan,
                  nan,          nan],
        [ 2.30848e+01,          nan,          nan, ...,          nan,
                  nan,          nan]], shape=(25, 100)),
 np.float64(1.0))

In [28]:
X_example = np.array(X_example, dtype="float64")
y_example = np.array(y_example)
X_example.shape, y_example.shape

((287, 25, 100), (287,))

In [29]:
from aeon.utils.tags import all_tags_for_estimator 
all_tags_for_estimator("classifier")

{'python_version': {'class': 'estimator',
  'type': ['str', None],
  'description': "Python version specifier (PEP 440) for estimator as str. e.g. '>=3.6', '>=3.7, <3.9'. If None, no restriction."},
 'python_dependencies': {'class': 'estimator',
  'type': ['list', 'str', None],
  'description': "Python dependency version specifier (PEP 440) for estimator as str or list of str. e.g. 'tsfresh>=0.20.0', '[tsfresh>=0.20.0, pandas<2.0.0]'. If None, no restriction."},
 'non_deterministic': {'class': 'estimator',
  'type': 'bool',
  'description': 'The estimator is non-deterministic, and multiple runs will not produce the same output even if a `random_state` is set.'},
 'cant_pickle': {'class': 'estimator',
  'type': 'bool',
  'description': 'The estimator cannot be pickled.'},
 'X_inner_type': {'class': 'estimator',
  'type': [('list||str',
    ['numpy3D',
     'np-list',
     'df-list',
     'numpy2D',
     'pd-wide',
     'pd-multiindex',
     'pd.Series',
     'pd.DataFrame',
     'np.nda

In [30]:
ppeclf.fit(X_example, y_example) # should handle missing values

ProgressivePrefixEnsembleClassifier()

In [31]:
ppeclf._classification_points, len(ppeclf._classification_points)

([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 10)

In [32]:
X_example[0], y_example[0]

(array([[ 1.00000e+00,  2.00000e+00,  3.00000e+00, ...,  9.80000e+01,
          9.90000e+01,  1.00000e+02],
        [-1.80000e-03,  4.30000e-03,  1.80000e-03, ..., -1.00000e-04,
         -3.40000e-03,  7.60000e-03],
        [ 6.00000e-04, -3.00000e-04,  3.00000e-04, ...,  3.00000e-04,
         -4.00000e-04, -1.00000e-04],
        ...,
        [ 1.00000e+02,  1.00000e+02,  1.00000e+02, ...,  1.00000e+02,
          1.00000e+02,  1.00000e+02],
        [ 3.89400e+01,  3.90600e+01,  3.91100e+01, ...,  3.90800e+01,
          3.91500e+01,  3.88500e+01],
        [ 2.34585e+01,  2.34085e+01,  2.34250e+01, ...,  2.35011e+01,
          2.33414e+01,  2.33310e+01]], shape=(25, 100)),
 np.float64(0.0))

In [33]:
ppeclf.predict(X_example[0:1])

([array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.])],
 [array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]]),
  array([[1., 0.]])])

In [34]:
X_example[100:101], y_example[100:101]

(array([[[ 1.01000e+02,  1.02000e+02,  1.03000e+02, ...,  1.98000e+02,
           1.99000e+02,  2.00000e+02],
         [ 3.10000e-03,  1.60000e-03, -2.20000e-03, ..., -5.10000e-03,
           2.60000e-03, -1.70000e-03],
         [-0.00000e+00,  1.00000e-04,  2.00000e-04, ...,  3.00000e-04,
           1.00000e-04,  0.00000e+00],
         ...,
         [ 1.00000e+02,  1.00000e+02,  1.00000e+02, ...,  1.00000e+02,
           1.00000e+02,  1.00000e+02],
         [ 3.89300e+01,  3.89200e+01,  3.91200e+01, ...,  3.89000e+01,
           3.90800e+01,  3.89500e+01],
         [ 2.34257e+01,  2.33453e+01,  2.34403e+01, ...,  2.32813e+01,
           2.32433e+01,  2.34101e+01]]], shape=(1, 25, 100)),
 array([1.]))

In [35]:
ppeclf.predict(X_example[100:101])

([array([1.]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.]),
  array([1.])],
 [array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]]),
  array([[0., 1.]])])

In [36]:
ppeclf.predict(X_example[85:88])

([array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.]),
  array([0., 0., 1.])],
 [array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]]),
  array([[1., 0.],
         [1., 0.],
         [0., 1.]])])

TODO 
* Implement __probability_treshold.py, __teaser.py, _timestamp.py
* DONE thresholds equally spaces instead of linearly
* study how teaser deals with training data for the estimator and teaser alg
* compare on various alpha combination
* compute metrics
* load test data

In [37]:
X = []
y = []
for Xi, yi in train:
    X += [Xi[:, j:j+prefix_max_length] for j in range(Xi.shape[1]-prefix_max_length+1)]
    y += [yi[j] for j in range(prefix_max_length-1, Xi.shape[1])]

In [38]:
X = np.array(X, dtype="float64")
y = np.array(y)
X.shape, y.shape

((9909, 25, 100), (9909,))

In [39]:
ppeclf.fit(X[:1000,:,:], y[:1000])

ProgressivePrefixEnsembleClassifier()

In [40]:
ppeclf._classification_points

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [53]:
test_data_path = "../data/nasa_cmapss/test_FD001.txt"
test = Dataset(test_data_path)
X_test = {i:{} for i in range(ppeclf._classification_points[0], prefix_max_length+1)} # key is number of filled values, subkey is case id
y_test = {i:{} for i in range(ppeclf._classification_points[0], prefix_max_length+1)}
for i, (Xi, yi) in enumerate(test):
    Xi_test = []
    yi_test = []
    # Filter only those without enough filled values
    for j in range(Xi.shape[1]-prefix_max_length+1):
        len_filled = np.sum(~np.isnan(Xi[:, j:j+prefix_max_length])) // Xi.shape[0] # minimum filled values (depending on number of variables)
        print(len_filled)
        if len_filled < ppeclf._classification_points[0]: 
            print(f"Skipping test case due to excessive number of NaNs")
            continue
        else:
            Xi_test.append(Xi[:, j:j+len_filled])
            yi_test.append(yi[j])
            X_test[len_filled][i] = Xi_test
            y_test[len_filled][i] = yi_test

100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
Skipping test case due to excessive number of NaNs
8
Skipping test case due to excessive number of NaNs
7
Skipping test case due to excessive number of NaNs
6
Skipping test case due to excessive number of NaNs
5
Skipping test case due to excessive number of NaNs
4
Skipping test case due to e

In [67]:
len(X_test[10][2]) # len 10, 30 cases, varying number of subseries per case

204

In [ ]:
X_test[10][0][0].shape

(25, 100)

In [54]:
X_test_10 = np.array(list(X_test[10].values()))
X_test_10.shape

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (30,) + inhomogeneous part.

In [43]:
ppeclf.predict(X_test_10)

([array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
         0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])],
 [array([[0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [1., 0.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [1., 0.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.]])])

In [51]:
len(X_test[100][0])

25

In [ ]:
ppeclf.predict(np.array(list(X_test[100].values())))

([array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
  array([1., 1., 1.,